# Generated by Django 3.0.4 on 2020-03-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishtype',
            old_name='fish_type',
            new_name='fish_type_name',
        ),
    ]
