# Generated by Django 3.0.4 on 2020-03-25 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20200320_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='fish',
            new_name='fish_name',
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
