# Generated by Django 3.0.4 on 2020-03-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_auto_20200325_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='fishes',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fish_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
