# Generated by Django 3.0.4 on 2020-03-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0007_auto_20200325_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='fish',
            new_name='fish_name',
        ),
    ]
